apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-app
    kubernetes.azure.com/generator: devhub
  name: test-app
  namespace: namespace-workflow-1734327461146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: jundachenacr.azurecr.io/rust-url-shortener
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 8080
        resources: {}
status: {}
