apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1734327461146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: jundachenacr.azurecr.io/rust-url-shortener:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
