// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;

#[derive(Queryable, Debug)]
pub struct Link {
    pub id: i32,
    pub short_link: String,
    pub full_link: String,
    pub create_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Stat {
    pub id: i32,
    pub ip: String,
    pub short_link: String,
    pub access_url: String,
}

