// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;

#[derive(Queryable, Debug)]
pub struct Jump {
    pub id: i32,
    pub from: String,
    pub to: String,
    pub create_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Stat {
    pub id: i32,
    pub ip: String,
    pub from: String,
    pub url: String,
}
